# ==============================================================================
# Hyprland Configuration — Apple macOS Design Language & Dark Theme
# ==============================================================================

# Environment Variables for GTK, Cursor & Qt Themes
env = GTK_THEME,WhiteSur-Dark
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORMTHEME,kde

decoration {
    blur {
        enabled = true
        size = 10
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = true
        vibrancy = 0.70
        vibrancy_darkness = 0.15
    }
}
