general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim screen at 2.5 min
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# Lock session at 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Screen off at 5.5 min
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend system at 15 min
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
